apiVersion: v1
kind: Service
metadata:
  name: angular-hw4-service
  namespace: hw4

spec:
  type: ClusterIP
  selector:
    app: angular-hw4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80