apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-hw4-dep
  namespace: hw4
  labels:
    app: angular-hw4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-hw4
  template:
    metadata:
      labels:
        app: angular-hw4 
    spec:
      containers:
        - name: angular-hw4
          image: angeela/angular-hw4:5
          imagePullPolicy: Always
          ports:
          # - containerPort: 80
          - containerPort: 53812

          # Just spin & wait forever
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      imagePullSecrets:
        - name: secret1
          
