apiVersion: v1
kind: Service
metadata:
  name: angular-hw4
  namespace: hw4
  labels:
    app: angular-hw4
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 53812
    protocol: TCP
    targetPort: web
